pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('API (Newman)') {
            steps {
                sh '''
                  newman run api-tests/*.postman_collection.json \
                    -e api-tests/*.postman_environment.json
                '''
            }
        }
    }
}